version: "3.8"

services:

  mpd:
    build: ./mpd
    ports:
      - "6660:6600"
    volumes:
      - /home/johannes/Music/:/var/lib/mpd/music/:ro
      - /home/johannes/Documents/docker/snapcast-mdp-alpine/varlib/:/var/lib/mpd/
      - streamfile:/tmp
    
  snapserver:
    build: ./snapserver
    ports:
        - "6861:1704"
        - "6862:1705"
        - "6863:1780"
    volumes:
        - streamfile:/tmp

volumes:
  streamfile:
    name: streamfile
