version: "3.8"

services:

  mpd:
    build: ./mpd
    ports:
      - "6660:6600"
    volumes:
      - /home/johannes/MusicNA/:/var/lib/mpd/music/:ro
      - /home/johannes/Documents/docker/snapcast-mdp-alpine/varlib/:/var/lib/mpd/
      - streamfile:/tmp
    
  snapserver:
    build: ./snapserver
    ports:
        - "6661:1704"
        - "6662:1705"
        - "6663:1780"
    volumes:
        - streamfile:/tmp

volumes:
  streamfile:
    name: streamfile
